### ISSUE TITLE
A few remarks

### ISSUE THREAD

**Issue by etiennebacher** [jonthegeek/wapir#24]
Hi @jonthegeek, I saw your post on Mastodon but I don't have an account there so I'm just writing a few remarks here (only based on my cursory reading of chapter 2):

* you could talk a bit about the package [polite](https://dmi3kno.github.io/polite/), probably when you talk about robots.txt
* I find that the position of this chapter is strange. IMO scraping should be the last resort to get data from the web (related to you asking "Is it worth scraping?" in 2.4), so this chapter should be placed after the current chapter 8
* I'd say dynamic scraping could have its own chapter where you also talk about [making POST requests](https://www.etiennebacher.com/posts/2023-05-09-making-post-requests-with-r/) as an alternative to dynamic scraping.
* depending on when you finish this book, you could talk about a draft PR in the `rvest` repo that brings dynamic webscraping to `rvest` (using `chromote` under the hood).

That's it, just my two cents, best of luck with your book 😃

**Comment by jonthegeek** [comment]
Thanks @etiennebacher !
> * I find that the position of this chapter is strange. IMO scraping should be the last resort to get data from the web (related to you asking "Is it worth scraping?" in 2.4), so this chapter should be placed after the current chapter 8

I actually didn't intend to include scraping at all at first... but I think it can work as an introduction to the idea of exploring HTML/XML as a return format (and the idea that you're usually getting back some sort of text, which you can then explore with various tools), and a gentle lead in. Using an API is scary to a lot of people, so I wanted something that's a little more approachable.

I'll definitely be pointing out that all the rvest stuff is effectively GETs once we get there.

The more people make suggestions about the Dynamic side of things, the more I think it might end up being its own chapter. I *do* hope to use the rvest PR (after checking on stability there), and then I'm hoping I can walk people through using it but transitioning into POST when/if that makes sense (for a simpler-to-rerun process). I'll... have to play with more concrete examples to see what makes sense to cover.

Thanks for the suggestions/notes!

**Comment by etiennebacher** [comment]
> Using an API is scary to a lot of people, so I wanted something that's a little more approachable.

Actually I would have thought the opposite, I find scraping much more advanced and "scarier" than using an API. I might be biased because I actually don't use that many APIs and those that I use have a simple interface and a nice R package wrapping it. But still, using an API is usually a more robust and documented way to get data than scraping.

Also, maybe I'm a bit inexperienced in this area but I don't understand why knowing HTML and CSS (which is required for scraping) helps with APIs. Isn't the goal of APIs to provide an easier data access by only making requests? That's why I wouldn't put it first, in my mind it's not actually required to understand APIs.

I guess if I had to write a book on this (fortunately I don't have to 😅) I'd rather do:

1. **Using an API:** definition, how to use, how to wrap an API in a package. This forces the reader to familiarize with GET and POST requests and the `httr`/`httr2` packages
2. **Alternative to APIs**: when no API is available, webscraping (static or dynamic)
3. **Building your API**: current chapters 9-12 (I'm not familiar at all with this)

Again, just throwing ideas in the air in case it's helpful, no pressure ;)

**Comment by jonthegeek** [comment]
Thanks for the suggestions!
